char * binary_operation(char * bin1, char * bin2);
void bin_to_dec (char * bin);
char * bin_to_even_base (char * bin, int size_of_dig);
void final_conversion(char* output, char output_base, int output_is_negative);
char * one_oct_to_bin (char oct);
char * one_hex_to_bin (char hex);
char one_bin_to_oct (char * bin);
char one_bin_to_hex (char * bin);
char * oct_to_bin (char * oct);
char * dec_to_bin (char * dec);
char * hex_to_bin (char * hex);